# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  shoppingapi:
    image: shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile
    ports:
      - 80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
